name: go build

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    uses: meta/workflows/.forgejo/workflows/go-build.yml@master
    runs-on: docker
  notcp:
    uses: meta/workflows/.forgejo/workflows/go-build.yml@master
    runs-on: docker
    with:
      tags: notcp
  notailscale:
    uses: meta/workflows/.forgejo/workflows/go-build.yml@master
    runs-on: docker
    with:
      tags: notailscale
  noredis:
    uses: meta/workflows/.forgejo/workflows/go-build.yml@master
    runs-on: docker
    with:
      tags: noredis
